#!/bin/bash

# vital variables for the function of this script
QPKG_CONF="/etc/config/qpkg.conf"
QPKG_NAME="QMaven3"
QPKG_ROOT=$(/sbin/getcfg $QPKG_NAME Install_Path -f $QPKG_CONF)

#
# Maven Home Folder
#

# some programs MAY still reference:
export MAVEN_HOME="$QPKG_ROOT/mvn-3.5.4"

# nowadays, documentation ONLY mentions:
export M2_HOME="$MAVEN_HOME"

# and what is this?
export M2="$M2_HOME/bin"

#
# PATH
#

# but only if the entry is not present yet
if [ -z "$(/bin/echo $PATH | /bin/grep mvn-3.5.4)" ]; then
	# export PATH=$(/bin/echo ${PATH} | /bin/awk -v RS=: -v ORS=: "/mvn-3.5.4/ {next} {print}" | /bin/sed 's/:*$//')
	export PATH="$PATH:$M2"
fi

#
# Maven Opts
#

source "$QPKG_ROOT/../.maven/maven_opts"
