#!/bin/bash

# vital variables for the function of this script
QPKG_CONF="/etc/config/qpkg.conf"
QPKG_NAME="QMaven3"
QPKG_ROOT="$(/sbin/getcfg $QPKG_NAME Install_Path -f $QPKG_CONF)"

# declare data folders and files
MVN_DATA_FOLDER="$QPKG_ROOT/../.maven"
MVN_DATA_MO="$MVN_DATA_FOLDER/set_env_mvn"

$CMD_TOUCH "$MVN_DATA_MO"
		$CMD_ECHO -e "# export MAVEN_OPTS=" >> "$MVN_DATA_MO"

# declare files within the persistent directory
	# TODO:
	MVN_DATA_MO="$MVN_DATA_FOLDER/set_env_mvn"

# setup Maven environment
echo "--- Setting up PATH..."
export PATH="$QPKG_ROOT/dist/bin:$PATH"
if [ -f "$MVN_DATA_JH" ]; then
	echo "--- Setting up JAVA_HOME (user preference)..."
	/bin/sh "$MVN_DATA_JH"
fi

if [ -f "$MVN_DATA_MO" ]; then
	echo "--- Setting up MAVEN_OPTS (user preference)..."
	/bin/sh "$MVN_DATA_MO"
fi

# and finish up
echo "Success!"
exit 0

# Run "mvn --version" to verify that it is correctly installed.
# Confirm with mvn -v in a new shell
